receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
        
processors:
  batch:
  resource:
    attributes:
      - key: telemetry.sdk.name
        action: delete
      - key: telemetry.sdk.language
        action: delete
      - key: telemetry.sdk.version
        action: delete
      - key: service.name
        action: delete
        
  attributes:
    actions:
      - key: LogRecord.CategoryName
        action: delete
      - key: LogRecord.ScopeValues
        action: delete
        
exporters:
  otlp:
    protocols:
      grpc:
        endpoint: file.telemetry.dashboard:18889
  
service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch, resource, attributes]
      exporters: [otlp]
    traces:
      receivers: [otlp]
      processors: [batch, resource, attributes]
      exporters: [otlp]