receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
        
processors:
  batch:
    
exporters:
  otlp:
    protocols:
      grpc:
        endpoint: file.telemetry.dashboard:18889
  
service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]